### ISSUE TITLE
Add Code for Selection Sort.

### ISSUE THREAD

**Issue by Ritik-7** [houseofgeeks/CP-Dictionary#11]
Add a code for Selection Sort following the contributing guidelines.

**Comment by shiv-ani-singh** [comment]
Can you assign this to me?

**Comment by anktrj** [comment]
Hi, @shiv-ani-singh assigned it to you!
Let the PR rain!

**Comment by sanskarseth** [comment]
@shiv-ani-singh are you on this issue?

**Comment by sanskarseth** [comment]
I am assigning this to myself as its too long and no response was there.
