### ISSUE TITLE
Implement Inversion Count in a permutation using BIT

### ISSUE THREAD

**Issue by anktrj** [houseofgeeks/CP-Dictionary#113]
Add code form `Inversion count in a permutation using BIT`

**Comment by Whitedevil1206** [comment]
Does it mean we have to write a program to calculate how far is an array from being sorted like in arr=[4,3,1,2]  answer should be 5 using binary indexed tree ?

**Comment by anktrj** [comment]
Yup exactly!

**Comment by Whitedevil1206** [comment]
Oh ok, i would like to try that, can you assign this to me, i would get to learn more about trees through this.
