### ISSUE TITLE
Add codes in different languages

### ISSUE THREAD

**Issue by vishalvibes** [houseofgeeks/CP-Dictionary#166]
Add codes of simpler algorithms like linear search, etc. in more language.

A good start will be python3, golang, javascript, C#...

But anything that's known is wholeheartedly welcomed!

**Note: This issue is for adding codes, that are already there in the directory, in different languages. If you want to add different algorithms then raise an issue first and then make a pull request.**

**Comment by gaurangisinha** [comment]
Hello, @Vishal19111999 Could I please contribute to this issue?

**Comment by vishalvibes** [comment]
@gaurangisinha ya sure !

**Comment by FaryalAjradh** [comment]
Is this issue still open?

**Comment by shubhamnag14** [comment]
Can i contribute to this issue

**Comment by vishalvibes** [comment]
@shubhamnag14 ya sure!

**Comment by paraggoyal28** [comment]
@Vishal19111999  I would like to contribute to this issue also. May I ?

**Comment by vishalvibes** [comment]
@paraggoyal28 sure but do mention here the algo and language of which you are writing code

**Comment by siddharthshekharr** [comment]
@Vishal19111999 I want to add Linear Search code using Java

**Comment by vishalvibes** [comment]
@HarthSid sure Siddharth, go ahead!

**Comment by snehaa1989** [comment]
Can i add Merge sort code using C++?

**Comment by vishalvibes** [comment]
@snehaa1989 ya go ahead!

**Comment by adarsh115** [comment]
hey @Vishal19111999 can I contribute C++ code for the Dijkstra algorithm

**Comment by vishalvibes** [comment]
@adarsh115 ya sure!

**Comment by adarsh115** [comment]
> @adarsh115 ya sure!

ok. I added code and made a pr

**Comment by sanskarseth** [comment]
@adarsh115 you have closed your pull request. Please reopen it.

**Comment by subhadeep-123** [comment]
i would like to contribute a algorithm in c++
kindly assign me one

**Comment by sanskarseth** [comment]
@subhadeep-123 go through the directory and find an algorithm that is not there then raise an issue and make a pull request.
Different Algorithms and codes for algorithms that are there in different languages are welcomed 😇.

**Comment by 123mansha** [comment]
hey@ Vishal19111999 i added a STACKQ9(stack program )in C
please review it.

**Comment by 123mansha** [comment]
@Vishal19111999  I made a pr #192

**Comment by sanskarseth** [comment]
@123mansha please raise an issue first as the current issue is for implementing the codes that are already there in other languages.

**Comment by 123mansha** [comment]
@sanskarseth  I added the code for insertion sort in the existing Insertion_Sort folder #192 
Please check it and tell me it its right..
I raised an issue also #193

**Comment by AK-codingmaniac** [comment]
Hello @Vishal19111999 @sanskarseth I would like to add some sorting and searching programs in javascript language.Can I?
