### ISSUE TITLE
Add code for Prefix-Suffix array generation

### ISSUE THREAD

**Issue by prskid1000** [houseofgeeks/CP-Dictionary#24]
### Description
One is required to created code for generating prefix array and suffix array of the given array.

**Comment by YourAKShaw** [comment]
Kindly assign this issue to me.

**Comment by sanskarseth** [comment]
Hey, @Ak-Shaw are you into this.

**Comment by YourAKShaw** [comment]
Been a l'il busy lately. Will get it done by today.
