### ISSUE TITLE
Add code for Extended Euclidean Algorithm

### ISSUE THREAD

**Issue by prskid1000** [houseofgeeks/CP-Dictionary#27]
### Description

One is required to write code for extended euclidean algorithm.

**Comment by itskeffect** [comment]
Kindly assign this to me!

**Comment by sanskarseth** [comment]
Assigning to you @itskeffect

**Comment by sanskarseth** [comment]
@itskeffect are you into it ?

**Comment by itskeffect** [comment]
Yes will upload it soon.
