### ISSUE TITLE
Add code for finding no. of nodes in a subtree.

### ISSUE THREAD

**Issue by sanskarseth** [houseofgeeks/CP-Dictionary#42]
### Description

Add code for finding total no. of nodes in a subtree.

**Comment by dhruvrkashyap** [comment]
So, a head pointer of a tree is given, and we have to find the total number of nodes in attached with it?

**Comment by anktrj** [comment]
> So, a head pointer of a tree is given, and we have to find the total number of nodes in attached with it?

You can assume node 1 is the root!

**Comment by dhruvrkashyap** [comment]
> You can assume node 1 is the root!

Can you assign this issue to me?

**Comment by Ritik-7** [comment]
hey @dhruvrkashyap are you into it or shall i get it done?

**Comment by dhruvrkashyap** [comment]
> hey @dhruvrkashyap are you into it or shall i get it done?

I will be doing it as a part of hacktoberfest

**Comment by sanskarseth** [comment]
@dhruvrkashyap we are giving you one more day time for doing this, if you are unable to do this then this issue will be assigned to someone else.

**Comment by sanskarseth** [comment]
@dhruvrkashyap we cannot wait for that much longer so I am assigning this issue to @Ritik-7 and don't worry you will be getting many more good first issues at the time of hactoberfest.

**Comment by dhruvrkashyap** [comment]
Hey, i have made a pull request, did you get it?

**Comment by sanskarseth** [comment]
nopes, you have to make pr to the master branch
